### ISSUE TITLE
can not download this file “TBSSimulationDatabase20170330.mat”

### ISSUE THREAD

**Issue by zouxu634866** [jingego/HK_Polyu_VTOL_Sim#1]
Hi, @jingego ：
I'd like to quote your research results and found your open source program on GitHub. But when I use the " git lfs clone https://github.com/jingego/HK_Polyu_VTOL_Sim.git", the system prompts “batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access” .

Could you provide us with other ways to get this file "TBSSimulationDatabase20170330.mat"，such as online disk.

We look forward to your reply！！

**Comment by jingego** [comment]
hi, please send me your email address. I will invite you to the share link;

**Comment by zouxu634866** [comment]
Hi, @jingego ,thanks for your reply. My email address is "zouxu634866@mail.nwpu.edu.cn"
